### ISSUE TITLE
config init callback

### ISSUE THREAD

**Issue by keathley** [keathley/vapor#8]
We need to provide an init callback for the config behaviour so that users can arbitrarily decide to take actions once the configuration has been retrieved.

**Comment by cheerfulstoic** [comment]
Is it possible to config an `init` callback?  I see [this section](https://github.com/keathley/vapor/tree/master#overriding-application-environment) in the `README` which I think says that you can, but when I try it doesn't call the function.  I've tried 0.2.0 and `master` (switching to the `Plan` module accordingly for `master`)

The reason I'm trying to do this is because `twittex` uses [`Application.fetch_env!`](https://github.com/almightycouch/twittex/blob/5643b4e6caadd81009944c97c687b32702c77ac2/lib/twittex/client/base.ex#L332) in a couple of places, so I'm trying to set application variables before `twittex` is loaded (the way to do that seems to be to set `runtime: false` for the dep in `mix.exs` and then to put it into `extra_applications`).  I'd be happy to have a better way if you know of one ;)

**Comment by keathley** [comment]
This is going to be solved in #51
